# site settings
title: Junkiejem
subtitle: Front-End Engineer | Web Developer
email: jemaiimanao@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: # the subpath of your site, e.g. /blog
url: "https://junkiejem.github.io" # the base hostname & protocol for your site
author:
street_address: 
city: Las Pinas City
state: Manila
zip_code: 1740
country: Philippines
mobile/phone: (+63)917 858 2523

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://junkiejem.github.io
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/junkiejem
linkedin_url: https://www.linkedin.com/in/joana-elizabeth-manao-2b65b240/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/junkiejem

# build settings
markdown: kramdown
theme: junkiejem.github.io

sass:
  style: compressed
